# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ここはどこでしょう?@アサノ研
#email: 18t2003g@shinshu-u.ac.jp
description: 写真からどこで，なにを撮影したものかを推理してください。
baseurl: "/kokodoko" # the subpath of your site, e.g. /blog
url: "http://asano-lab.github.io" # the base hostname & protocol for your site
github_username: asano-lab

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist

