# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ここはどこでしょう?@アサノ研
#email: 18t2003g@shinshu-u.ac.jp
description: >
  写真からどこで，なにを撮影したものかを推理してください。
  信州大学工学部　電子情報システム工学科　アサノ研究室 
baseurl: "/kokodoko" # the subpath of your site, e.g. /blog
url: "http://18t2003@.github.io" # the base hostname & protocol for your site
github_username: 18t2003g

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
